### ISSUE TITLE
CORS issues with Twitter API

### ISSUE THREAD

**Issue by kanedafromparis** [PerfectSlayer/twitter-raffle#1]
;-)

**Comment by PerfectSlayer** [comment]
Seriously? I will need a better description than this one...

In my case, I only use it with Firefox and keep in mind Firefox blocks Twitter script for privacy.

**Comment by kanedafromparis** [comment]
No problem for better description.
This draft was a reminder.
I was in a hurry yesterday.

Basically, when on Firefox, the button don't have any effect, I didn't see
any issues in the console.
It was just a regular check before the session so I was in hurry.
I use a mac (os-x) just to notice.

Some of the possible issues could be that I use EFF plugin bagger.
 It works when I switched to chrome.

**Comment by PerfectSlayer** [comment]
Oh yeah... I had a quick look.
It is not only with Firefox but with any browser that applies CORS. The issue comes from the Twitter API that does not handle it.

I need to rework the whole thing to do server side rendering instead of client side rendering... meaning I will need to handle multiple users on server side now and maybe move from DOM/JS to HTML template.

It might take some hours =/

**Comment by sunix** [comment]
Hey 
1. I don't think we still have cors issue. as far as I remember I got rid of that, and it works on firefox on my side:
![Selection_458](https://user-images.githubusercontent.com/650571/133618126-85c6e18b-c223-4d73-ade2-7c22aa55d4de.png)
2. plz create issue/PR here: https://github.com/parisjug/twitter-raffle

**Comment by sunix** [comment]
https://github.com/parisjug/twitter-raffle/commit/c8ab9be6cad3d6a12bc0157376eab6850487f031

**Comment by PerfectSlayer** [comment]
I fixed the issue in the next version using a simpler approach (still client side).

Thanks to keep posting issue on the upstream project.
